/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-07-08 18:10:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.todo.app.dto.User;
import com.todo.app.dto.Todo;
import java.util.Set;
import java.util.*;
import java.text.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.20.RELEASE.jar", Long.valueOf(1657301752437L));
    _jspx_dependants.put("jar:file:/G:/CDACM2022/SRC-Module-6/AdvanceJava%20Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Todo-List-Project/WEB-INF/lib/spring-webmvc-4.3.20.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1539572356000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.todo.app.dto.User");
    _jspx_imports_classes.add("com.todo.app.dto.Todo");
    _jspx_imports_classes.add("java.util.Set");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("\n");
      out.write("\n");
      out.write("      \n");
      out.write("      \n");
      out.write("      \n");
      out.write("          \n");
      out.write("              \n");
      out.write("    \n");
      out.write("\n");

response.setHeader("Cache-Control","no-cache");
response.setHeader("Cache-Control","no-store");
response.setHeader("Pragma","no-cache");
response.setDateHeader ("Expires", 0);
    if(session.getAttribute("user")==null){
    response.sendRedirect(request.getContextPath() + "/index.jsp");

    }

      out.write('\n');

	User user2 = (User)session.getAttribute("user");
	String userName = "", profilePic = "";
	if(user2!=null){
		userName = user2.getUserFullName();
		profilePic = user2.getProfilePic();
	}

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <!-- Tell the browser to be responsive to screen width -->\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"\">\n");
      out.write("    <!-- Favicon icon -->\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"assets/images/favicon.png\">\n");
      out.write("    <title>Dashboard</title>\n");
      out.write("    <!-- Bootstrap Core CSS -->\n");
      out.write("    <link href=\"assets/plugins/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Custom CSS -->\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- You can change the theme colors from here -->\n");
      out.write("    <link href=\"css/colors/blue.css\" id=\"theme\" rel=\"stylesheet\">\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("    <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\n");
      out.write("    <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\n");
      out.write("<![endif]-->\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"fix-header card-no-border\">\n");
 User user = (User)session.getAttribute("user");

      out.write("\n");
      out.write("    <!-- ============================================================== -->\n");
      out.write("    <!-- Preloader - style you can find in spinners.css -->\n");
      out.write("    <!-- ============================================================== -->\n");
      out.write("    <div class=\"preloader\">\n");
      out.write("        <svg class=\"circular\" viewBox=\"25 25 50 50\">\n");
      out.write("            <circle class=\"path\" cx=\"50\" cy=\"50\" r=\"20\" fill=\"none\" stroke-width=\"2\" stroke-miterlimit=\"10\" /> </svg>\n");
      out.write("    </div>\n");
      out.write("    <!-- ============================================================== -->\n");
      out.write("    <!-- Main wrapper - style you can find in pages.scss -->\n");
      out.write("    <!-- ============================================================== -->\n");
      out.write("    <div id=\"main-wrapper\">\n");
      out.write("        <!-- ============================================================== -->\n");
      out.write("        <!-- Topbar header - style you can find in pages.scss -->\n");
      out.write("        <!-- ============================================================== -->\n");
      out.write("        <header class=\"topbar\">\n");
      out.write("            <nav class=\"navbar top-navbar navbar-toggleable-sm navbar-light\">\n");
      out.write("                <!-- ============================================================== -->\n");
      out.write("                <!-- Logo -->\n");
      out.write("                <!-- ============================================================== -->\n");
      out.write("                <div class=\"navbar-header\">\n");
      out.write("                    <a class=\"navbar-brand\" href=\"index.html\">\n");
      out.write("                        <!-- Logo icon -->\n");
      out.write("                        <b>\n");
      out.write("                            <!--You can put here icon as well // <i class=\"wi wi-sunset\"></i> //-->\n");
      out.write("                            <!-- Dark Logo icon -->\n");
      out.write("                            <img src=\"image/logo.png\" alt=\"homepage\" width=\"200\" class=\"dark-logo\" />\n");
      out.write("                            \n");
      out.write("                        </b>\n");
      out.write("                        <!--End Logo icon -->\n");
      out.write("                        <!-- Logo text -->\n");
      out.write("                        <span>\n");
      out.write("                         <!-- dark Logo text \n");
      out.write("                         <img src=\"assets/images/logo-text.png\" alt=\"homepage\" class=\"dark-logo\" />\n");
      out.write("                         </span> </a>\n");
      out.write("                         -->\n");
      out.write("                </div>\n");
      out.write("                <!-- ============================================================== -->\n");
      out.write("                <!-- End Logo -->\n");
      out.write("                <!-- ============================================================== -->\n");
      out.write("                <div class=\"navbar-collapse\">\n");
      out.write("                    <!-- ============================================================== -->\n");
      out.write("                    <!-- toggle and nav items -->\n");
      out.write("                    <!-- ============================================================== -->\n");
      out.write("                    <ul class=\"navbar-nav mr-auto mt-md-0 \">\n");
      out.write("                        <!-- This is  -->\n");
      out.write("                        <li class=\"nav-item\"> <a class=\"nav-link nav-toggler hidden-md-up text-muted waves-effect waves-dark\" href=\"javascript:void(0)\"><i class=\"ti-menu\"></i></a> </li>\n");
      out.write("                        <li class=\"nav-item hidden-sm-down\">\n");
      out.write("                           \n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                        						<h2>Welcome ... ");
      out.print( user.getUserFullName());
      out.write("</h2>\n");
      out.write("                                     <div>\n");
      out.write("		&nbsp;&nbsp;</div>       \n");
      out.write("                    </ul>\n");
      out.write("                    <!-- ============================================================== -->\n");
      out.write("                    <!-- User profile and search -->\n");
      out.write("                    <!-- ============================================================== -->\n");
      out.write("                    <ul class=\"navbar-nav my-lg-0\">\n");
      out.write("                   \n");
      out.write("                        <li class=\"nav-item dropdown\">\n");
      out.write("         						<a class=\"btn btn-primary\" href=\"logout.app\">logout</a></li>\n");
      out.write("                        \n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </nav>\n");
      out.write("        </header>\n");
      out.write("        <!-- ============================================================== -->\n");
      out.write("        <!-- End Topbar header -->\n");
      out.write("        <!-- ============================================================== -->\n");
      out.write("        <!-- ============================================================== -->\n");
      out.write("        <!-- Left Sidebar - style you can find in sidebar.scss  -->\n");
      out.write("        <!-- ============================================================== -->\n");
      out.write("        <aside class=\"left-sidebar\">\n");
      out.write("            <!-- Sidebar scroll-->\n");
      out.write("            <div class=\"scroll-sidebar\">\n");
      out.write("                <!-- Sidebar navigation-->\n");
      out.write("                <nav class=\"sidebar-nav\">\n");
      out.write("                    <ul id=\"sidebarnav\" \">\n");
      out.write("                         <li class=\"waves-effect ml-5\">\n");
      out.write("							<img alt=\"no pic\" style=\"border-radius:40%;\" onerror=\"this.src='image/default.webp';\"  src=\"");
      out.print("images/"+profilePic);
      out.write("\" height=\"150\" width=\"150\" >                         </li>\n");
      out.write("                      </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"#\" class=\"waves-effect\"><i class=\"fa fa-clock-o m-r-10\" aria-hidden=\"true\"></i>Dashboard</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"userProfile.app\" class=\"waves-effect\"><i class=\"fa fa-user m-r-10\" aria-hidden=\"true\"></i>Profile</a>\n");
      out.write("                        </li>\n");
      out.write("                        \n");
      out.write("                    </ul>\n");
      out.write("                    <div class=\"text-center m-t-30\">\n");
      out.write(" 						<li>\n");
      out.write("                            <a href=\"Fileupload_form.jsp\" class=\"waves-effect\"><i class=\"fa fa-columns m-r-10\" aria-hidden=\"true\"></i>PROFILE PICTURE</a>\n");
      out.write("                        </li>\n");
      out.write("                    </div>\n");
      out.write("                </nav>\n");
      out.write("                <!-- End Sidebar navigation -->\n");
      out.write("            </div>\n");
      out.write("            <!-- End Sidebar scroll-->\n");
      out.write("        </aside>\n");
      out.write("        <!-- ============================================================== -->\n");
      out.write("        <!-- End Left Sidebar - style you can find in sidebar.scss  -->\n");
      out.write("        <!-- ============================================================== -->\n");
      out.write("        <!-- ============================================================== -->\n");
      out.write("        <!-- Page wrapper  -->\n");
      out.write("        <!-- ============================================================== -->\n");
      out.write("        <div class=\"page-wrapper\">\n");
      out.write("            <!-- ============================================================== -->\n");
      out.write("            <!-- Container fluid  -->\n");
      out.write("            <!-- ============================================================== -->\n");
      out.write("            <div class=\"container-fluid\">\n");
      out.write("                <!-- ============================================================== -->\n");
      out.write("                <!-- Bread crumb and right sidebar toggle -->\n");
      out.write("                <!-- ============================================================== -->\n");
      out.write("                <div class=\"row page-titles\">\n");
      out.write("                    <div class=\"col-md-6 col-8 align-self-center\">\n");
      out.write("                        <h3 class=\"text-themecolor m-b-0 m-t-0\">Dashboard</h3>\n");
      out.write("                        <ol class=\"breadcrumb\">\n");
      out.write("                            <li class=\"breadcrumb-item\"><a href=\"javascript:void(0)\">Home</a></li>\n");
      out.write("                            <li class=\"breadcrumb-item active\">Dashboard</li>\n");
      out.write("                        </ol>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-6 col-4 align-self-center\">\n");
      out.write("                    \n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- ============================================================== -->\n");
      out.write("                <!-- End Bread crumb and right sidebar toggle -->\n");
      out.write("                <!-- ============================================================== -->\n");
      out.write("                <!-- ============================================================== -->\n");
      out.write("                <!-- Start Page Content -->\n");
      out.write("                <!-- ============================================================== -->\n");
      out.write("                \n");
      out.write("                \n");
      out.write("                \n");
      out.write("                \n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <!-- column -->\n");
      out.write("                    <div class=\"col-sm-12\">\n");
      out.write("                        <div class=\"card\">\n");
      out.write("                            <div class=\"card-block\">\n");
      out.write("                            \n");
      out.write("                            <button type=\"button\" class=\"btn btn-lg btn-danger\" data-toggle=\"modal\" data-target=\"#exampleModalCenter\">\n");
      out.write("  						Add\n");
      out.write("					</button>   \n");
      out.write("                                <h1 class=\"card-title mt-5\">Task List</h1>\n");
      out.write("							                            \n");
      out.write("					 <form class=\"app-search p-l-20\">\n");
      out.write("                              <a class=\"mr-2 border srh-btn\"><i class=\"ti-search\"></i></a><input type=\"text\" class=\"form-control col-8\" id=\"myInput\" placeholder=\"Search for...\"> \n");
      out.write("                            </form>\n");
      out.write("					  <div class=\"table-responsive\">\n");
      out.write("                                    <table class=\"table\" style=\" \">\n");
      out.write("                                        <thead>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <th>#</th>\n");
      out.write("                                                <th>Title</th>\n");
      out.write("                                                <th>Description</th>\n");
      out.write("                                                <th>Target Date</th>\n");
      out.write("                                                <th>Comment</th>\n");
      out.write("                                                \n");
      out.write("                                            </tr>\n");
      out.write("                                        </thead>\n");
      out.write("                                        <tbody id=\"myTable\">\n");
      out.write("                                           \n");
      out.write(" 								");
 
                                int i = 1;

 								List<Todo> todoli = (List<Todo>)session.getAttribute("todoList");

                                            for(Todo t : todoli) {
      out.write("\n");
      out.write("                                             <tr>\n");
      out.write("                                                <td>");
      out.print(i);
      out.write("</td>\n");
      out.write("                                                <td>");
      out.print( t.getTitle());
      out.write("</td>\n");
      out.write("                                                <td style=\"word-break: break-all;\">");
      out.print( t.getDescription());
      out.write("</td>\n");
      out.write("                                                <td>");
      out.print( t.getTargetDate());
      out.write("</td>                                                \n");
      out.write("                                                <td>");
      out.print( t.getComment());
      out.write("</td>\n");
      out.write("                                                <td><a href=\"updateTaskForm.app?taskId=");
      out.print(t.getTaskId());
      out.write("\" class=\"btn btn-primary btn-lg active\" role=\"button\" aria-pressed=\"true\">update</a>\n");
      out.write("                                                </td>\n");
      out.write("                                                     <td><a onclick=\"if(!(confirm('Are You Sure you want to delete ?'))) return false\"  href=\"deleteTask.app?taskId=");
      out.print(t.getTaskId());
      out.write("\" class=\"btn btn-danger btn-lg active\" role=\"button\" aria-pressed=\"true\">delete</a>\n");
      out.write("                                                </td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            \n");
      out.write("                                            ");
 i++; } 
      out.write("                                        </tbody>\n");
      out.write("                                    </table>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- ============================================================== -->\n");
      out.write("                <!-- End PAge Content -->\n");
      out.write("                <!-- ============================================================== -->\n");
      out.write("            </div>\n");
      out.write("            <!-- ============================================================== -->\n");
      out.write("            <!-- End Container fluid  -->\n");
      out.write("            <!-- ============================================================== -->\n");
      out.write("            <!-- ============================================================== -->\n");
      out.write("            <!-- footer -->\n");
      out.write("            <!-- ============================================================== -->\n");
      out.write("            <footer class=\"footer text-center\">\n");
      out.write("                © 2022 Todo-List\n");
      out.write("            </footer>\n");
      out.write("            <!-- ============================================================== -->\n");
      out.write("            <!-- End footer -->\n");
      out.write("            <!-- ============================================================== -->\n");
      out.write("        </div>\n");
      out.write("        <!-- ============================================================== -->\n");
      out.write("        <!-- End Page wrapper  -->\n");
      out.write("        <!-- ============================================================== -->\n");
      out.write("    </div>\n");
      out.write("    <!-- ============================================================== -->\n");
      out.write("    <!-- End Wrapper -->\n");
      out.write("    <!-- ============================================================== -->\n");
      out.write("    <!-- ============================================================== -->\n");
      out.write("    <!-- All Jquery -->\n");
      out.write("    <!-- ============================================================== -->\n");
      out.write("    <script src=\"assets/plugins/jquery/jquery.min.js\"></script>\n");
      out.write("    <!-- Bootstrap tether Core JavaScript -->\n");
      out.write("    <script src=\"assets/plugins/bootstrap/js/tether.min.js\"></script>\n");
      out.write("    <script src=\"assets/plugins/bootstrap/js/bootstrap.min.js\"></script>\n");
      out.write("    <!-- slimscrollbar scrollbar JavaScript -->\n");
      out.write("    <script src=\"js/jquery.slimscroll.js\"></script>\n");
      out.write("    <!--Wave Effects -->\n");
      out.write("    <script src=\"js/waves.js\"></script>\n");
      out.write("    <!--Menu sidebar -->\n");
      out.write("    <script src=\"js/sidebarmenu.js\"></script>\n");
      out.write("    <!--stickey kit -->\n");
      out.write("    <script src=\"assets/plugins/sticky-kit-master/dist/sticky-kit.min.js\"></script>\n");
      out.write("    <!--Custom JavaScript -->\n");
      out.write("    <script src=\"js/custom.min.js\"></script>\n");
      out.write("    <!-- ============================================================== -->\n");
      out.write("    <!-- Style switcher -->\n");
      out.write("    <!-- ============================================================== -->\n");
      out.write("    <script src=\"assets/plugins/styleswitcher/jQuery.style.switcher.js\"></script>\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("	$(document).ready(function(){\n");
      out.write("  		$(\"#myInput\").on(\"keyup\", function() {\n");
      out.write("    		var value = $(this).val().toLowerCase();\n");
      out.write("    	$(\"#myTable tr\").filter(function() {\n");
      out.write("      		$(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)\n");
      out.write("    	});\n");
      out.write("  		});\n");
      out.write("		});\n");
      out.write("	\n");
      out.write("	\n");
      out.write("\n");
      out.write("	</script>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <!-- Modal -->\n");
      out.write("<div class=\"modal fade\" id=\"exampleModalCenter\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalCenterTitle\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("      <div class=\"modal-header\">\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\">Task form</h5>\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("        </button>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("        <form action=\"addTask.app\" method=\"post\">\n");
      out.write("  <div class=\"form-row\">\n");
      out.write("    <div class=\"form-group col-md-12\">\n");
      out.write("      <label for=\"title\">Title</label>\n");
      out.write("      <input type=\"text\" required=\"Title is required\" name=\"title\"class=\"form-control\"  maxlength=\"15\"  minlength=\"3\" id=\"title\" placeholder=\"Enter task title\">\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group col-md-12\">\n");
      out.write("      <label for=\"description\">Description</label>\n");
      out.write("      <textarea type=\"text\" required=\"Description is required\" maxlength=\"30\"  minlength=\"5\" name=\"description\" class=\"form-control\" id=\"description\" placeholder=\"Enter full description\"></textarea>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"form-group col-md-12\"\">\n");
      out.write("    <label for=\"date\">Target Date</label>\n");
      out.write("    ");
 Date d = new Date();
    	SimpleDateFormat sm = new SimpleDateFormat("yyyy/mm/dd");

    		String d1 = sm.format(d);
    		System.out.println("Date:"+d1);
    
      out.write("\n");
      out.write("    <input  class=\"form-control inspectionDate\" required=\"Date is required\"  type=\"date\" name=\"targetDate\"  id=\"txtDate\" >\n");
      out.write("    \n");
      out.write("    \n");
      out.write("  </div>\n");
      out.write("  <div class=\"form-group col-md-12\"\">\n");
      out.write("    <label for=\"comment\">Comment</label>\n");
      out.write("    <textarea type=\"text\" maxlength=\"30\" required=\"Comment is required\"  minlength=\"3\" name=\"comment\" class=\"form-control\" id=\"inputAddress2\" placeholder=\"Apartment, studio, or floor\"></textarea>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  <div class=\"modal-footer\">\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\n");
      out.write("        <input type=\"submit\" class=\"btn btn-primary\" value=\"add task\">\n");
      out.write("  </div>\n");
      out.write(" </form>\n");
      out.write("      </div>\n");
      out.write("    \n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("$( document ).ready(function() {\n");
      out.write("	console.log(new Date().toISOString())\n");
      out.write("	\n");
      out.write("	var date = new Date().toISOString().slice(0,10);\n");
      out.write("\n");
      out.write("	//To restrict past date\n");
      out.write("\n");
      out.write("	$('#txtDate').attr('min', date);\n");
      out.write("\n");
      out.write("	//To restrict future date\n");
      out.write("\n");
      out.write("	$('#txtDate').attr('max', \"3030-01-01\");\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
