/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-07-08 17:58:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.todo.app.dto.User;
import com.todo.app.dto.Todo;
import java.util.Set;
import java.util.List;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.20.RELEASE.jar", Long.valueOf(1657301752437L));
    _jspx_dependants.put("jar:file:/G:/CDACM2022/SRC-Module-6/AdvanceJava%20Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Todo-List-Project/WEB-INF/lib/spring-webmvc-4.3.20.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1539572356000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.todo.app.dto.User");
    _jspx_imports_classes.add("com.todo.app.dto.Todo");
    _jspx_imports_classes.add("java.util.Set");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftodo_005fform_0026_005fmethod_005fcommandName_005fclass_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftodo_005finput_0026_005ftype_005fpath_005fclass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftodo_005finput_0026_005ftype_005freadonly_005fpath_005fid_005fclass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftodo_005fhidden_0026_005fvalue_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftodo_005ferrors_0026_005fpath_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftodo_005fform_0026_005fmethod_005fcommandName_005fclass_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftodo_005finput_0026_005ftype_005fpath_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftodo_005finput_0026_005ftype_005freadonly_005fpath_005fid_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftodo_005fhidden_0026_005fvalue_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftodo_005ferrors_0026_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftodo_005fform_0026_005fmethod_005fcommandName_005fclass_005faction.release();
    _005fjspx_005ftagPool_005ftodo_005finput_0026_005ftype_005fpath_005fclass_005fnobody.release();
    _005fjspx_005ftagPool_005ftodo_005finput_0026_005ftype_005freadonly_005fpath_005fid_005fclass_005fnobody.release();
    _005fjspx_005ftagPool_005ftodo_005fhidden_0026_005fvalue_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005ftodo_005ferrors_0026_005fpath_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("        \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <!-- Tell the browser to be responsive to screen width -->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("    <!-- Favicon icon -->\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"assets/images/favicon.png\">\r\n");
      out.write("    <title>Profile</title>\r\n");
      out.write("    <!-- Bootstrap Core CSS -->\r\n");
      out.write("    <link href=\"assets/plugins/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- You can change the theme colors from here -->\r\n");
      out.write("    <link href=\"css/colors/blue.css\" id=\"theme\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"fix-header card-no-border\">\r\n");
 User user = (User)session.getAttribute("user");

      out.write("\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- Preloader - style you can find in spinners.css -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <div class=\"preloader\">\r\n");
      out.write("        <svg class=\"circular\" viewBox=\"25 25 50 50\">\r\n");
      out.write("            <circle class=\"path\" cx=\"50\" cy=\"50\" r=\"20\" fill=\"none\" stroke-width=\"2\" stroke-miterlimit=\"10\" /> </svg>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- Main wrapper - style you can find in pages.scss -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <div id=\"main-wrapper\">\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- Topbar header - style you can find in pages.scss -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <header class=\"topbar\">\r\n");
      out.write("            <nav class=\"navbar top-navbar navbar-toggleable-sm navbar-light\">\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- Logo -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <div class=\"navbar-header\">\r\n");
      out.write("                    <a class=\"navbar-brand\" href=\"index.html\">\r\n");
      out.write("                        <!-- Logo icon -->\r\n");
      out.write("                        <b>\r\n");
      out.write("                            <!--You can put here icon as well // <i class=\"wi wi-sunset\"></i> //-->\r\n");
      out.write("                            <!-- Dark Logo icon -->\r\n");
      out.write("                            <img src=\"image/logo.png\" alt=\"homepage\" width=\"200\" class=\"dark-logo\" />\r\n");
      out.write("                            \r\n");
      out.write("                        </b>\r\n");
      out.write("                        <!--End Logo icon -->\r\n");
      out.write("                        <!-- Logo text -->\r\n");
      out.write("                        \r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- End Logo -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <div class=\"navbar-collapse\">\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- toggle and nav items -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <ul class=\"navbar-nav mr-auto mt-md-0 \">\r\n");
      out.write("                        <!-- This is  -->\r\n");
      out.write("                        <li class=\"nav-item\"> <a class=\"nav-link nav-toggler hidden-md-up text-muted waves-effect waves-dark\" href=\"javascript:void(0)\"><i class=\"ti-menu\"></i></a> </li>\r\n");
      out.write("                      						  <p class=\"mt-2 ml-2\">");
      out.print( user.getUserFullName());
      out.write("</p>\r\n");
      out.write("                      \r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- User profile and search -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <ul class=\"navbar-nav my-lg-0\">\r\n");
      out.write("                         <li class=\"nav-item dropdown\">\r\n");
      out.write("         						<a class=\"btn btn-primary\" href=\"logout.app\">logout</a></li>\r\n");
      out.write("                        \r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- End Topbar header -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- Left Sidebar - style you can find in sidebar.scss  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <aside class=\"left-sidebar\">\r\n");
      out.write("            <!-- Sidebar scroll-->\r\n");
      out.write("            <div class=\"scroll-sidebar\">\r\n");
      out.write("                <!-- Sidebar navigation-->\r\n");
      out.write("                <nav class=\"sidebar-nav\">\r\n");
      out.write("                    <ul id=\"sidebarnav\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"backToDashboard.app\" class=\"waves-effect\"><i class=\"fa fa-clock-o m-r-10\" aria-hidden=\"true\"></i>Dashboard</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"pages-profile.html\" class=\"waves-effect\"><i class=\"fa fa-user m-r-10\" aria-hidden=\"true\"></i>Profile</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                       \r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <div class=\"text-center m-t-30\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <!-- End Sidebar navigation -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- End Sidebar scroll-->\r\n");
      out.write("        </aside>\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- End Left Sidebar - style you can find in sidebar.scss  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- Page wrapper  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <div class=\"page-wrapper\">\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- Container fluid  -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- Bread crumb and right sidebar toggle -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <div class=\"row page-titles\">\r\n");
      out.write("                    <div class=\"col-md-6 col-8 align-self-center\">\r\n");
      out.write("                        <h3 class=\"text-themecolor m-b-0 m-t-0\">Profile</h3>\r\n");
      out.write("                        <ol class=\"breadcrumb\">\r\n");
      out.write("                            <li class=\"breadcrumb-item\"><a href=\"javascript:void(0)\">Home</a></li>\r\n");
      out.write("                            <li class=\"breadcrumb-item active\">Profile</li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                    </div>\r\n");
      out.write("                 \r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- End Bread crumb and right sidebar toggle -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- Start Page Content -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- Row -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <!-- Column -->\r\n");
      out.write("                 \r\n");
      out.write("                    <!-- Column -->\r\n");
      out.write("                    <!-- Column -->\r\n");
      out.write("                    <div class=\"col-lg-8 col-xlg-9 col-md-7\">\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <div class=\"card-block\">\r\n");
      out.write("                                ");
      //  todo:form
      org.springframework.web.servlet.tags.form.FormTag _jspx_th_todo_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005ftodo_005fform_0026_005fmethod_005fcommandName_005fclass_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
      boolean _jspx_th_todo_005fform_005f0_reused = false;
      try {
        _jspx_th_todo_005fform_005f0.setPageContext(_jspx_page_context);
        _jspx_th_todo_005fform_005f0.setParent(null);
        // /profile.jsp(163,32) null
        _jspx_th_todo_005fform_005f0.setDynamicAttribute(null, "class", "form-horizontal form-material");
        // /profile.jsp(163,32) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_todo_005fform_005f0.setAction("doProfileUpdate.app");
        // /profile.jsp(163,32) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_todo_005fform_005f0.setMethod("post");
        // /profile.jsp(163,32) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_todo_005fform_005f0.setCommandName("user");
        int[] _jspx_push_body_count_todo_005fform_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_todo_005fform_005f0 = _jspx_th_todo_005fform_005f0.doStartTag();
          if (_jspx_eval_todo_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("                                    <div class=\"form-group\">\r\n");
              out.write("                                        <label class=\"col-md-12\">Full Name</label>\r\n");
              out.write("                                        <div class=\"col-md-12\">\r\n");
              out.write("                                            ");
              if (_jspx_meth_todo_005finput_005f0(_jspx_th_todo_005fform_005f0, _jspx_page_context, _jspx_push_body_count_todo_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("                                        </div>\r\n");
              out.write("                                    </div>\r\n");
              out.write("                                    <div class=\"form-group\">\r\n");
              out.write("                                        <label for=\"example-email\" class=\"col-md-12\">Email</label>\r\n");
              out.write("                                        <div class=\"col-md-12\">\r\n");
              out.write("                                           <!--  ");
              if (_jspx_meth_todo_005finput_005f1(_jspx_th_todo_005fform_005f0, _jspx_page_context, _jspx_push_body_count_todo_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("                                       -->\r\n");
              out.write("                                       ");
 User user1 = (User)session.getAttribute("user");
                                       		
                                       
              out.write("\r\n");
              out.write("                                       ");
              out.print( user1.getUserEmail() );
              out.write("\r\n");
              out.write("                                        ");
              //  todo:hidden
              org.springframework.web.servlet.tags.form.HiddenInputTag _jspx_th_todo_005fhidden_005f0 = (org.springframework.web.servlet.tags.form.HiddenInputTag) _005fjspx_005ftagPool_005ftodo_005fhidden_0026_005fvalue_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.HiddenInputTag.class);
              boolean _jspx_th_todo_005fhidden_005f0_reused = false;
              try {
                _jspx_th_todo_005fhidden_005f0.setPageContext(_jspx_page_context);
                _jspx_th_todo_005fhidden_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_todo_005fform_005f0);
                // /profile.jsp(179,40) null
                _jspx_th_todo_005fhidden_005f0.setDynamicAttribute(null, "value",  user1.getUserEmail());
                // /profile.jsp(179,40) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_todo_005fhidden_005f0.setPath("userEmail");
                int[] _jspx_push_body_count_todo_005fhidden_005f0 = new int[] { 0 };
                try {
                  int _jspx_eval_todo_005fhidden_005f0 = _jspx_th_todo_005fhidden_005f0.doStartTag();
                  if (_jspx_th_todo_005fhidden_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_todo_005fhidden_005f0[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_todo_005fhidden_005f0.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_todo_005fhidden_005f0.doFinally();
                }
                _005fjspx_005ftagPool_005ftodo_005fhidden_0026_005fvalue_005fpath_005fnobody.reuse(_jspx_th_todo_005fhidden_005f0);
                _jspx_th_todo_005fhidden_005f0_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_todo_005fhidden_005f0, _jsp_getInstanceManager(), _jspx_th_todo_005fhidden_005f0_reused);
              }
              out.write("\r\n");
              out.write("                                       \r\n");
              out.write("                                        </div>\r\n");
              out.write("                                    </div>\r\n");
              out.write("                                    <div class=\"form-group\">\r\n");
              out.write("                                        <label class=\"col-md-12\">Password</label>\r\n");
              out.write("                                        <div class=\"col-md-12\">\r\n");
              out.write("                                           ");
              if (_jspx_meth_todo_005finput_005f2(_jspx_th_todo_005fform_005f0, _jspx_page_context, _jspx_push_body_count_todo_005fform_005f0))
                return;
              out.write(" \r\n");
              out.write("                                      \r\n");
              out.write("                                        </div>\r\n");
              out.write("                                    </div>\r\n");
              out.write("                                   \r\n");
              out.write("                                   \r\n");
              out.write("                                    <div class=\"form-group\">\r\n");
              out.write("                                        <div class=\"col-sm-12\">\r\n");
              out.write("                                            <input type=\"submit\" value=\"Update Profile\" class=\"btn btn-success\">\r\n");
              out.write("                                        </div>\r\n");
              out.write("                                    </div>\r\n");
              out.write("                                    <font color=\"red\" >");
              //  todo:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_todo_005ferrors_005f0 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005ftodo_005ferrors_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_todo_005ferrors_005f0_reused = false;
              try {
                _jspx_th_todo_005ferrors_005f0.setPageContext(_jspx_page_context);
                _jspx_th_todo_005ferrors_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_todo_005fform_005f0);
                // /profile.jsp(197,55) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_todo_005ferrors_005f0.setPath("userFullName");
                int[] _jspx_push_body_count_todo_005ferrors_005f0 = new int[] { 0 };
                try {
                  int _jspx_eval_todo_005ferrors_005f0 = _jspx_th_todo_005ferrors_005f0.doStartTag();
                  if (_jspx_th_todo_005ferrors_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_todo_005ferrors_005f0[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_todo_005ferrors_005f0.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_todo_005ferrors_005f0.doFinally();
                }
                _005fjspx_005ftagPool_005ftodo_005ferrors_0026_005fpath_005fnobody.reuse(_jspx_th_todo_005ferrors_005f0);
                _jspx_th_todo_005ferrors_005f0_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_todo_005ferrors_005f0, _jsp_getInstanceManager(), _jspx_th_todo_005ferrors_005f0_reused);
              }
              out.write("</font>\r\n");
              out.write("                                    <font color=\"red\" >");
              //  todo:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_todo_005ferrors_005f1 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005ftodo_005ferrors_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_todo_005ferrors_005f1_reused = false;
              try {
                _jspx_th_todo_005ferrors_005f1.setPageContext(_jspx_page_context);
                _jspx_th_todo_005ferrors_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_todo_005fform_005f0);
                // /profile.jsp(198,55) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_todo_005ferrors_005f1.setPath("userPassword");
                int[] _jspx_push_body_count_todo_005ferrors_005f1 = new int[] { 0 };
                try {
                  int _jspx_eval_todo_005ferrors_005f1 = _jspx_th_todo_005ferrors_005f1.doStartTag();
                  if (_jspx_th_todo_005ferrors_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_todo_005ferrors_005f1[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_todo_005ferrors_005f1.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_todo_005ferrors_005f1.doFinally();
                }
                _005fjspx_005ftagPool_005ftodo_005ferrors_0026_005fpath_005fnobody.reuse(_jspx_th_todo_005ferrors_005f1);
                _jspx_th_todo_005ferrors_005f1_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_todo_005ferrors_005f1, _jsp_getInstanceManager(), _jspx_th_todo_005ferrors_005f1_reused);
              }
              out.write("</font>\r\n");
              out.write("                                    <font color=\"red\" >");
              //  todo:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_todo_005ferrors_005f2 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005ftodo_005ferrors_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_todo_005ferrors_005f2_reused = false;
              try {
                _jspx_th_todo_005ferrors_005f2.setPageContext(_jspx_page_context);
                _jspx_th_todo_005ferrors_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_todo_005fform_005f0);
                // /profile.jsp(199,55) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_todo_005ferrors_005f2.setPath("userEmail");
                int[] _jspx_push_body_count_todo_005ferrors_005f2 = new int[] { 0 };
                try {
                  int _jspx_eval_todo_005ferrors_005f2 = _jspx_th_todo_005ferrors_005f2.doStartTag();
                  if (_jspx_th_todo_005ferrors_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_todo_005ferrors_005f2[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_todo_005ferrors_005f2.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_todo_005ferrors_005f2.doFinally();
                }
                _005fjspx_005ftagPool_005ftodo_005ferrors_0026_005fpath_005fnobody.reuse(_jspx_th_todo_005ferrors_005f2);
                _jspx_th_todo_005ferrors_005f2_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_todo_005ferrors_005f2, _jsp_getInstanceManager(), _jspx_th_todo_005ferrors_005f2_reused);
              }
              out.write("</font>\r\n");
              out.write("					<c:if test=\"condition\"></c:if>\r\n");
              out.write("					<c:choose>\r\n");
              out.write("    					<c:when test=\"");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${already!=null}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\">\r\n");
              out.write("							<div class=\"alert alert-danger\" role=\"alert\">");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${already}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</div><br />\r\n");
              out.write("   					 </c:when>    \r\n");
              out.write("			   		 <c:otherwise>\r\n");
              out.write("  					     <br />\r\n");
              out.write("   					 </c:otherwise>\r\n");
              out.write("					 </c:choose>                                   ");
              int evalDoAfterBody = _jspx_th_todo_005fform_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_todo_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_todo_005fform_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_todo_005fform_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_todo_005fform_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005ftodo_005fform_0026_005fmethod_005fcommandName_005fclass_005faction.reuse(_jspx_th_todo_005fform_005f0);
        _jspx_th_todo_005fform_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_todo_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_todo_005fform_005f0_reused);
      }
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Column -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Row -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- End PAge Content -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- End Container fluid  -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- footer -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <footer class=\"footer text-center\">\r\n");
      out.write("                Â© 2020 Todo-List\r\n");
      out.write("            </footer>\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- End footer -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- End Page wrapper  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- End Wrapper -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- All Jquery -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <script src=\"assets/plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Bootstrap tether Core JavaScript -->\r\n");
      out.write("    <script src=\"assets/plugins/bootstrap/js/tether.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/plugins/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- slimscrollbar scrollbar JavaScript -->\r\n");
      out.write("    <script src=\"js/jquery.slimscroll.js\"></script>\r\n");
      out.write("    <!--Wave Effects -->\r\n");
      out.write("    <script src=\"js/waves.js\"></script>\r\n");
      out.write("    <!--Menu sidebar -->\r\n");
      out.write("    <script src=\"js/sidebarmenu.js\"></script>\r\n");
      out.write("    <!--stickey kit -->\r\n");
      out.write("    <script src=\"assets/plugins/sticky-kit-master/dist/sticky-kit.min.js\"></script>\r\n");
      out.write("    <!--Custom JavaScript -->\r\n");
      out.write("    <script src=\"js/custom.min.js\"></script>\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- Style switcher -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <script src=\"assets/plugins/styleswitcher/jQuery.style.switcher.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_todo_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_todo_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_todo_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  todo:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_todo_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005ftodo_005finput_0026_005ftype_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_todo_005finput_005f0_reused = false;
    try {
      _jspx_th_todo_005finput_005f0.setPageContext(_jspx_page_context);
      _jspx_th_todo_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_todo_005fform_005f0);
      // /profile.jsp(167,44) null
      _jspx_th_todo_005finput_005f0.setDynamicAttribute(null, "type", "text");
      // /profile.jsp(167,44) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_todo_005finput_005f0.setPath("userFullName");
      // /profile.jsp(167,44) null
      _jspx_th_todo_005finput_005f0.setDynamicAttribute(null, "class", "form-control form-control-line");
      int[] _jspx_push_body_count_todo_005finput_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_todo_005finput_005f0 = _jspx_th_todo_005finput_005f0.doStartTag();
        if (_jspx_th_todo_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_todo_005finput_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_todo_005finput_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_todo_005finput_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005ftodo_005finput_0026_005ftype_005fpath_005fclass_005fnobody.reuse(_jspx_th_todo_005finput_005f0);
      _jspx_th_todo_005finput_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_todo_005finput_005f0, _jsp_getInstanceManager(), _jspx_th_todo_005finput_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_todo_005finput_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_todo_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_todo_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  todo:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_todo_005finput_005f1 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005ftodo_005finput_0026_005ftype_005freadonly_005fpath_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_todo_005finput_005f1_reused = false;
    try {
      _jspx_th_todo_005finput_005f1.setPageContext(_jspx_page_context);
      _jspx_th_todo_005finput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_todo_005fform_005f0);
      // /profile.jsp(173,49) null
      _jspx_th_todo_005finput_005f1.setDynamicAttribute(null, "type", "email");
      // /profile.jsp(173,49) name = readonly type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_todo_005finput_005f1.setReadonly(false);
      // /profile.jsp(173,49) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_todo_005finput_005f1.setPath("userEmail");
      // /profile.jsp(173,49) null
      _jspx_th_todo_005finput_005f1.setDynamicAttribute(null, "class", "form-control form-control-line");
      // /profile.jsp(173,49) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_todo_005finput_005f1.setId("example-email");
      int[] _jspx_push_body_count_todo_005finput_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_todo_005finput_005f1 = _jspx_th_todo_005finput_005f1.doStartTag();
        if (_jspx_th_todo_005finput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_todo_005finput_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_todo_005finput_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_todo_005finput_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005ftodo_005finput_0026_005ftype_005freadonly_005fpath_005fid_005fclass_005fnobody.reuse(_jspx_th_todo_005finput_005f1);
      _jspx_th_todo_005finput_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_todo_005finput_005f1, _jsp_getInstanceManager(), _jspx_th_todo_005finput_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_todo_005finput_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_todo_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_todo_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  todo:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_todo_005finput_005f2 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005ftodo_005finput_0026_005ftype_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_todo_005finput_005f2_reused = false;
    try {
      _jspx_th_todo_005finput_005f2.setPageContext(_jspx_page_context);
      _jspx_th_todo_005finput_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_todo_005fform_005f0);
      // /profile.jsp(186,43) null
      _jspx_th_todo_005finput_005f2.setDynamicAttribute(null, "type", "text ");
      // /profile.jsp(186,43) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_todo_005finput_005f2.setPath("userPassword");
      // /profile.jsp(186,43) null
      _jspx_th_todo_005finput_005f2.setDynamicAttribute(null, "class", "form-control form-control-line");
      int[] _jspx_push_body_count_todo_005finput_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_todo_005finput_005f2 = _jspx_th_todo_005finput_005f2.doStartTag();
        if (_jspx_th_todo_005finput_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_todo_005finput_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_todo_005finput_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_todo_005finput_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005ftodo_005finput_0026_005ftype_005fpath_005fclass_005fnobody.reuse(_jspx_th_todo_005finput_005f2);
      _jspx_th_todo_005finput_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_todo_005finput_005f2, _jsp_getInstanceManager(), _jspx_th_todo_005finput_005f2_reused);
    }
    return false;
  }
}
