/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-07-08 17:49:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.20.RELEASE.jar", Long.valueOf(1657301752437L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1657275043204L));
    _jspx_dependants.put("jar:file:/G:/CDACM2022/SRC-Module-6/AdvanceJava%20Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Todo-List-Project/WEB-INF/lib/spring-webmvc-4.3.20.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1539572356000L));
    _jspx_dependants.put("jar:file:/G:/CDACM2022/SRC-Module-6/AdvanceJava%20Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Todo-List-Project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftodo_005fform_0026_005fmethod_005fcommandName_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftodo_005finput_0026_005fplaceholder_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftodo_005ferrors_0026_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftodo_005finput_0026_005ftype_005fplaceholder_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftodo_005fform_0026_005fmethod_005fcommandName_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftodo_005finput_0026_005fplaceholder_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftodo_005ferrors_0026_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftodo_005finput_0026_005ftype_005fplaceholder_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftodo_005fform_0026_005fmethod_005fcommandName_005faction.release();
    _005fjspx_005ftagPool_005ftodo_005finput_0026_005fplaceholder_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005ftodo_005ferrors_0026_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005ftodo_005finput_0026_005ftype_005fplaceholder_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("        \n");
      out.write("        \n");
      out.write("    \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Register Form</title>\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/mystyle.css\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"></script>\n");
      out.write("	<link href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\"></head>\n");
      out.write("<body>\n");
      out.write("<div class=\"container-fluid\">\n");
      out.write("		<div class=\"row\">\n");
      out.write("			<div class=\"col-lg-6 col-md-6 d-none d-md-block image-container\">\n");
      out.write("						<img src=\"image/bg.jpg\" width=\"750px\" align=\"center\">\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"col-lg-6 col-md-6 form-container\">\n");
      out.write("				<div class=\"col-lg-8 col-md-12 col-sm-9 col-xs-12 form-box text-center\">\n");
      out.write("					<div class=\"logo mb-3\">\n");
      out.write("						<img src=\"image/logo.png\" width=\"150px\">\n");
      out.write("					</div>\n");
      out.write("					<div class=\"heading mb-4\">\n");
      out.write("						<h4>Create an account</h4>\n");
      out.write("					</div>\n");
      out.write("					");
      //  todo:form
      org.springframework.web.servlet.tags.form.FormTag _jspx_th_todo_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005ftodo_005fform_0026_005fmethod_005fcommandName_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
      boolean _jspx_th_todo_005fform_005f0_reused = false;
      try {
        _jspx_th_todo_005fform_005f0.setPageContext(_jspx_page_context);
        _jspx_th_todo_005fform_005f0.setParent(null);
        // /signup.jsp(31,5) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_todo_005fform_005f0.setAction("doSignup.app");
        // /signup.jsp(31,5) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_todo_005fform_005f0.setMethod("post");
        // /signup.jsp(31,5) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_todo_005fform_005f0.setCommandName("user");
        int[] _jspx_push_body_count_todo_005fform_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_todo_005fform_005f0 = _jspx_th_todo_005fform_005f0.doStartTag();
          if (_jspx_eval_todo_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\n");
              out.write("						<div class=\"form-input\">\n");
              out.write("							<span><i class=\"fa fa-user\"></i></span>\n");
              out.write("							");
              if (_jspx_meth_todo_005finput_005f0(_jspx_th_todo_005fform_005f0, _jspx_page_context, _jspx_push_body_count_todo_005fform_005f0))
                return;
              out.write("\n");
              out.write("						</div><font color=\"red\" >");
              //  todo:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_todo_005ferrors_005f0 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005ftodo_005ferrors_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_todo_005ferrors_005f0_reused = false;
              try {
                _jspx_th_todo_005ferrors_005f0.setPageContext(_jspx_page_context);
                _jspx_th_todo_005ferrors_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_todo_005fform_005f0);
                // /signup.jsp(35,31) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_todo_005ferrors_005f0.setPath("userFullName");
                int[] _jspx_push_body_count_todo_005ferrors_005f0 = new int[] { 0 };
                try {
                  int _jspx_eval_todo_005ferrors_005f0 = _jspx_th_todo_005ferrors_005f0.doStartTag();
                  if (_jspx_th_todo_005ferrors_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_todo_005ferrors_005f0[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_todo_005ferrors_005f0.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_todo_005ferrors_005f0.doFinally();
                }
                _005fjspx_005ftagPool_005ftodo_005ferrors_0026_005fpath_005fnobody.reuse(_jspx_th_todo_005ferrors_005f0);
                _jspx_th_todo_005ferrors_005f0_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_todo_005ferrors_005f0, _jsp_getInstanceManager(), _jspx_th_todo_005ferrors_005f0_reused);
              }
              out.write("</font>\n");
              out.write("                	\n");
              out.write("						<div class=\"form-input\">\n");
              out.write("							<span><i class=\"fa fa-envelope\"></i></span>\n");
              out.write("							");
              if (_jspx_meth_todo_005finput_005f1(_jspx_th_todo_005fform_005f0, _jspx_page_context, _jspx_push_body_count_todo_005fform_005f0))
                return;
              out.write("\n");
              out.write("						</div>\n");
              out.write("                    <font color=\"red\" >");
              //  todo:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_todo_005ferrors_005f1 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005ftodo_005ferrors_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_todo_005ferrors_005f1_reused = false;
              try {
                _jspx_th_todo_005ferrors_005f1.setPageContext(_jspx_page_context);
                _jspx_th_todo_005ferrors_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_todo_005fform_005f0);
                // /signup.jsp(41,39) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_todo_005ferrors_005f1.setPath("userEmail");
                int[] _jspx_push_body_count_todo_005ferrors_005f1 = new int[] { 0 };
                try {
                  int _jspx_eval_todo_005ferrors_005f1 = _jspx_th_todo_005ferrors_005f1.doStartTag();
                  if (_jspx_th_todo_005ferrors_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_todo_005ferrors_005f1[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_todo_005ferrors_005f1.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_todo_005ferrors_005f1.doFinally();
                }
                _005fjspx_005ftagPool_005ftodo_005ferrors_0026_005fpath_005fnobody.reuse(_jspx_th_todo_005ferrors_005f1);
                _jspx_th_todo_005ferrors_005f1_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_todo_005ferrors_005f1, _jsp_getInstanceManager(), _jspx_th_todo_005ferrors_005f1_reused);
              }
              out.write("</font>\n");
              out.write("				\n");
              out.write("						<div class=\"form-input\">\n");
              out.write("							<span><i class=\"fa fa-lock\"></i></span>\n");
              out.write("							");
              if (_jspx_meth_todo_005finput_005f2(_jspx_th_todo_005fform_005f0, _jspx_page_context, _jspx_push_body_count_todo_005fform_005f0))
                return;
              out.write("\n");
              out.write("						</div>\n");
              out.write("						<font color=\"red\" >");
              //  todo:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_todo_005ferrors_005f2 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005ftodo_005ferrors_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_todo_005ferrors_005f2_reused = false;
              try {
                _jspx_th_todo_005ferrors_005f2.setPageContext(_jspx_page_context);
                _jspx_th_todo_005ferrors_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_todo_005fform_005f0);
                // /signup.jsp(47,25) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_todo_005ferrors_005f2.setPath("userPassword");
                int[] _jspx_push_body_count_todo_005ferrors_005f2 = new int[] { 0 };
                try {
                  int _jspx_eval_todo_005ferrors_005f2 = _jspx_th_todo_005ferrors_005f2.doStartTag();
                  if (_jspx_th_todo_005ferrors_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_todo_005ferrors_005f2[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_todo_005ferrors_005f2.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_todo_005ferrors_005f2.doFinally();
                }
                _005fjspx_005ftagPool_005ftodo_005ferrors_0026_005fpath_005fnobody.reuse(_jspx_th_todo_005ferrors_005f2);
                _jspx_th_todo_005ferrors_005f2_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_todo_005ferrors_005f2, _jsp_getInstanceManager(), _jspx_th_todo_005ferrors_005f2_reused);
              }
              out.write("</font>\n");
              out.write("						\n");
              out.write("	\n");
              out.write("						<div class=\"text-left mb-3\">\n");
              out.write("							<button type=\"submit\" class=\"btn\">Register</button>\n");
              out.write("						</div>\n");
              out.write("					\n");
              out.write("						<div style=\"color: #777\">Already have an account\n");
              out.write("							<a href=\"userLogin.app\" class=\"login-link\">Login here</a>\n");
              out.write("						</div>\n");
              out.write("					");
              int evalDoAfterBody = _jspx_th_todo_005fform_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_todo_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_todo_005fform_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_todo_005fform_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_todo_005fform_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005ftodo_005fform_0026_005fmethod_005fcommandName_005faction.reuse(_jspx_th_todo_005fform_005f0);
        _jspx_th_todo_005fform_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_todo_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_todo_005fform_005f0_reused);
      }
      out.write("\n");
      out.write("\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("					");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("                                       \n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_todo_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_todo_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_todo_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  todo:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_todo_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005ftodo_005finput_0026_005fplaceholder_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_todo_005finput_005f0_reused = false;
    try {
      _jspx_th_todo_005finput_005f0.setPageContext(_jspx_page_context);
      _jspx_th_todo_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_todo_005fform_005f0);
      // /signup.jsp(34,7) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_todo_005finput_005f0.setPath("userFullName");
      // /signup.jsp(34,7) null
      _jspx_th_todo_005finput_005f0.setDynamicAttribute(null, "placeholder", "Full Name");
      int[] _jspx_push_body_count_todo_005finput_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_todo_005finput_005f0 = _jspx_th_todo_005finput_005f0.doStartTag();
        if (_jspx_th_todo_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_todo_005finput_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_todo_005finput_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_todo_005finput_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005ftodo_005finput_0026_005fplaceholder_005fpath_005fnobody.reuse(_jspx_th_todo_005finput_005f0);
      _jspx_th_todo_005finput_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_todo_005finput_005f0, _jsp_getInstanceManager(), _jspx_th_todo_005finput_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_todo_005finput_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_todo_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_todo_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  todo:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_todo_005finput_005f1 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005ftodo_005finput_0026_005ftype_005fplaceholder_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_todo_005finput_005f1_reused = false;
    try {
      _jspx_th_todo_005finput_005f1.setPageContext(_jspx_page_context);
      _jspx_th_todo_005finput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_todo_005fform_005f0);
      // /signup.jsp(39,7) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_todo_005finput_005f1.setPath("userEmail");
      // /signup.jsp(39,7) null
      _jspx_th_todo_005finput_005f1.setDynamicAttribute(null, "type", "email");
      // /signup.jsp(39,7) null
      _jspx_th_todo_005finput_005f1.setDynamicAttribute(null, "placeholder", "Email Address");
      int[] _jspx_push_body_count_todo_005finput_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_todo_005finput_005f1 = _jspx_th_todo_005finput_005f1.doStartTag();
        if (_jspx_th_todo_005finput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_todo_005finput_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_todo_005finput_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_todo_005finput_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005ftodo_005finput_0026_005ftype_005fplaceholder_005fpath_005fnobody.reuse(_jspx_th_todo_005finput_005f1);
      _jspx_th_todo_005finput_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_todo_005finput_005f1, _jsp_getInstanceManager(), _jspx_th_todo_005finput_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_todo_005finput_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_todo_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_todo_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  todo:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_todo_005finput_005f2 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005ftodo_005finput_0026_005ftype_005fplaceholder_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_todo_005finput_005f2_reused = false;
    try {
      _jspx_th_todo_005finput_005f2.setPageContext(_jspx_page_context);
      _jspx_th_todo_005finput_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_todo_005fform_005f0);
      // /signup.jsp(45,7) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_todo_005finput_005f2.setPath("userPassword");
      // /signup.jsp(45,7) null
      _jspx_th_todo_005finput_005f2.setDynamicAttribute(null, "type", "password");
      // /signup.jsp(45,7) null
      _jspx_th_todo_005finput_005f2.setDynamicAttribute(null, "placeholder", "Password");
      int[] _jspx_push_body_count_todo_005finput_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_todo_005finput_005f2 = _jspx_th_todo_005finput_005f2.doStartTag();
        if (_jspx_th_todo_005finput_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_todo_005finput_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_todo_005finput_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_todo_005finput_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005ftodo_005finput_0026_005ftype_005fplaceholder_005fpath_005fnobody.reuse(_jspx_th_todo_005finput_005f2);
      _jspx_th_todo_005finput_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_todo_005finput_005f2, _jsp_getInstanceManager(), _jspx_th_todo_005finput_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /signup.jsp(59,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(false);
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest_005fnobody.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("    					");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("    \n");
          out.write("			   		 ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("					 ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /signup.jsp(61,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UserExist!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("							<div class=\"alert alert-danger\" role=\"alert\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UserExist}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div><br />\n");
          out.write("   					 ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("  					     <br />\n");
          out.write("   					 ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
